### ISSUE TITLE
longstaff schwartz main example doesnt work 

### ISSUE THREAD

**Issue by dao72** [luphord/longstaff_schwartz#1]
* Longstaff-Schwartz Algorithm version:
* Python version:
* Operating System:

### Description

I copied the main example and it did not run. I get an error that polynomial is not properly conditioned
can you please fix
### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by luphord** [comment]
Which version of `numpy` are you running such that you get an *error* instead of a *warning* on the poorly conditioned fit?

Anyway, I have increased the number of simulated paths in the example which should make your issue go away. Can you confirm?

**Comment by dao72** [comment]
Hi. Will check.  The error went away after I cranked up number of paths to 500.

**Comment by luphord** [comment]
@dao72 Is there anything left to do from your point-of-view? Can this issue be closed?

**Comment by dao72** [comment]
Yes!
